tasks:
    path: /tasks
    controller: App\Controller\TaskController::index
    
task_detail:
    path: /detail/{id}
    controller: App\Controller\TaskController::detail
    
task_create:
    path: /create
    controller: App\Controller\TaskController::create

task_edit:
    path: /edit/{id}
    controller: App\Controller\TaskController::edit

task_delete:
    path: /delete/{id}
    controller: App\Controller\TaskController::delete
    
mytasks:
    path: /mytasks
    controller: App\Controller\TaskController::myTasks 
    
user_register:
    path: /register
    controller: App\Controller\UserController::register
    
login:
    path: /
    controller: App\Controller\UserController::login
    
logout:
    path: /logout
